
export  const generateHeightOptions = () => {
    const options = []
    for (let ft = 3; ft <= 7; ft++) {
      for (let inch = 0; inch < 12; inch++) {
        if (ft === 7 && inch > 0) break
        const label = `${ft}ft${inch > 0 ? ` ${inch}in` : ""}`
        const value = `${ft}.${inch.toString().padStart(2, "0")}`
        options.push({ label, value })
      }
    }
    return options
}


export const getDegreeOptions = (selectedQualification: string | undefined) => {
    switch (selectedQualification) {
      case 'intermediate':
        return [
          { value: 'associateDegreeAdministrationJustice', label: 'Associate Degree in Administration of Justice' },
          { value: 'associateDegreeAdvertising', label: 'Associate Degree in Advertising' },
          { value: 'associateDegreeAgribusiness', label: 'Associate Degree in Agribusiness' },
          { value: 'associateDegreeAnimalManagement', label: 'Associate Degree in Animal Management' },
          { value: 'associateDegreeArchitecturalBuilding', label: 'Associate Degree in Architectural Building Engineering Technology' },
          { value: 'faSimple', label: 'FA Simple' },
          { value: 'daeAfterMatric', label: 'DAE after Matric' },
          { value: 'ics', label: 'ICS' },
          { value: 'icom', label: 'I.Com' },
          { value: 'fsc', label: 'FSc' },
          { value: 'fscPreMedical', label: 'Fsc Pre Medical' },
          { value: 'fscPreEngineering', label: 'Fsc Pre Engineering' },
          { value: 'oaLevels', label: 'O/A Levels' }
        ]
      case 'bachelors':
        return [
          { value: 'bachelorArchitecture', label: 'Bachelor of Architecture' },
          { value: 'bachelorBiomedicalScience', label: 'Bachelor of Biomedical Science' },
          { value: 'bachelorBusinessAdministration', label: 'Bachelor of Business Administration' },
          { value: 'bachelorClinicalScience', label: 'Bachelor of Clinical Science' },
          { value: 'bachelorCommerce', label: 'Bachelor of Commerce' },
          { value: 'bachelorComputerApplications', label: 'Bachelor of Computer Applications' },
          { value: 'bachelorComputerInformationSystems', label: 'Bachelor of Computer Information Systems' },
          { value: 'bachelorScienceConstructionTechnology', label: 'Bachelor of Science in Construction Technology' },
          { value: 'bachelorCriminalJustice', label: 'Bachelor of Criminal Justice' },
          { value: 'bachelorDivinity', label: 'Bachelor of Divinity' },
          { value: 'bachelorEconomics', label: 'Bachelor of Economics' },
          { value: 'bachelorEducation', label: 'Bachelor of Education' },
          { value: 'bachelorEngineering', label: 'Bachelor of Engineering' },
          { value: 'bachelorFineArts', label: 'Bachelor of Fine Arts' },
          { value: 'bachelorInformationSystems', label: 'Bachelor of Information Systems' },
          { value: 'bachelorManagement', label: 'Bachelor of Management' },
          { value: 'bachelorMusic', label: 'Bachelor of Music' },
          { value: 'bachelorPharmacy', label: 'Bachelor of Pharmacy' },
          { value: 'bachelorPhilosophy', label: 'Bachelor of Philosophy' },
          { value: 'bachelorSocialWork', label: 'Bachelor of Social Work' },
          { value: 'bachelorTechnology', label: 'Bachelor of Technology' },
          { value: 'bachelorAccountancy', label: 'Bachelor of Accountancy' },
          { value: 'bachelorArtsAmericanStudies', label: 'Bachelor of Arts in American Studies' },
          { value: 'bachelorArtsAmericanIndianStudies', label: 'Bachelor of Arts in American Indian Studies' },
          { value: 'bachelorArtsAppliedPsychology', label: 'Bachelor of Arts in Applied Psychology' },
          { value: 'bachelorArtsBiology', label: 'Bachelor of Arts in Biology' },
          { value: 'bachelorArtsAnthropology', label: 'Bachelor of Arts in Anthropology' },
          { value: 'bachelorArtsChildAdvocacy', label: 'Bachelor of Arts in Child Advocacy' },
          { value: 'bachelorArtsClinicalPsychology', label: 'Bachelor of Arts in Clinical Psychology' },
          { value: 'bachelorArtsForensicPsychology', label: 'Bachelor of Arts in Forensic Psychology' },
          { value: 'bachelorArtsOrganizationalPsychology', label: 'Bachelor of Arts in Organizational Psychology' },
          { value: 'bachelorScienceAerospaceEngineering', label: 'Bachelor of Science in Aerospace Engineering' },
          { value: 'bachelorScienceActuarial', label: 'Bachelor of Science in Actuarial' },
          { value: 'bachelorScienceAgriculture', label: 'Bachelor of Science in Agriculture' },
          { value: 'bachelorScienceArchitecture', label: 'Bachelor of Science in Architecture' },
          { value: 'bachelorScienceArchitecturalEngineering', label: 'Bachelor of Science in Architectural Engineering' },
          { value: 'bachelorScienceBiology', label: 'Bachelor of Science in Biology' },
          { value: 'bachelorScienceBiomedicalEngineering', label: 'Bachelor of Science in Biomedical Engineering' },
          { value: 'bachelorScienceBusinessAdministration', label: 'Bachelor of Science in Business Administration' },
          { value: 'bachelorScienceBusinessTechnology', label: 'Bachelor of Science in Business and Technology' },
          { value: 'bachelorScienceChemicalEngineering', label: 'Bachelor of Science in Chemical Engineering' },
          { value: 'bachelorScienceChemistry', label: 'Bachelor of Science in Chemistry' },
          { value: 'bachelorScienceCivilEngineering', label: 'Bachelor of Science in Civil Engineering' },
          { value: 'bachelorScienceClinicalLaboratoryScience', label: 'Bachelor of Science in Clinical Laboratory Science' },
          { value: 'bachelorScienceCognitiveScience', label: 'Bachelor of Science in Cognitive Science' },
          { value: 'bachelorScienceComputerEngineering', label: 'Bachelor of Science in Computer Engineering' },
          { value: 'bachelorScienceComputerScience', label: 'Bachelor of Science in Computer Science' },
          { value: 'bachelorScienceConstructionEngineering', label: 'Bachelor of Science in Construction Engineering' },
          { value: 'bachelorScienceConstructionManagement', label: 'Bachelor of Science in Construction Management' },
          { value: 'bachelorScienceCriminalJustice', label: 'Bachelor of Science in Criminal Justice' },
          { value: 'bachelorScienceCriminology', label: 'Bachelor of Science in Criminology' },
          { value: 'bachelorScienceDiagnosticRadiography', label: 'Bachelor of Science in Diagnostic Radiography' },
          { value: 'bachelorScienceEducation', label: 'Bachelor of Science in Education' },
          { value: 'bachelorScienceElectricalEngineering', label: 'Bachelor of Science in Electrical Engineering' },
          { value: 'bachelorScienceEngineeringPhysics', label: 'Bachelor of Science in Engineering Physics' },
          { value: 'bachelorScienceEngineeringScience', label: 'Bachelor of Science in Engineering Science' },
          { value: 'bachelorScienceEngineeringTechnology', label: 'Bachelor of Science in Engineering Technology' },
          { value: 'bachelorScienceEnglishLiterature', label: 'Bachelor of Science in English Literature' },
          { value: 'bachelorScienceEnvironmentalEngineering', label: 'Bachelor of Science in Environmental Engineering' },
          { value: 'bachelorScienceEnvironmentalScience', label: 'Bachelor of Science in Environmental Science' },
          { value: 'bachelorScienceEnvironmentalStudies', label: 'Bachelor of Science in Environmental Studies' },
          { value: 'bachelorScienceFoodScience', label: 'Bachelor of Science in Food Science' },
          { value: 'bachelorScienceForeignService', label: 'Bachelor of Science in Foreign Service' },
          { value: 'bachelorScienceForensicScience', label: 'Bachelor of Science in Forensic Science' },
          { value: 'bachelorScienceForestry', label: 'Bachelor of Science in Forestry' },
          { value: 'bachelorScienceHistory', label: 'Bachelor of Science in History' },
          { value: 'bachelorScienceHospitalityManagement', label: 'Bachelor of Science in Hospitality Management' },
          { value: 'bachelorScienceHumanResourcesManagement', label: 'Bachelor of Science in Human Resources Management' },
          { value: 'bachelorScienceIndustrialEngineering', label: 'Bachelor of Science in Industrial Engineering' },
          { value: 'bachelorScienceInformationTechnology', label: 'Bachelor of Science in Information Technology' },
          { value: 'bachelorScienceInformationSystems', label: 'Bachelor of Science in Information Systems' },
          { value: 'bachelorScienceIntegratedScience', label: 'Bachelor of Science in Integrated Science' },
          { value: 'bachelorScienceInternationalRelations', label: 'Bachelor of Science in International Relations' },
          { value: 'bachelorScienceJournalism', label: 'Bachelor of Science in Journalism' },
          { value: 'bachelorScienceLegalManagement', label: 'Bachelor of Science in Legal Management' },
          { value: 'bachelorScienceManagement', label: 'Bachelor of Science in Management' },
          { value: 'bachelorScienceManufacturingEngineering', label: 'Bachelor of Science in Manufacturing Engineering' },
          { value: 'bachelorScienceMarketing', label: 'Bachelor of Science in Marketing' },
          { value: 'bachelorScienceMathematics', label: 'Bachelor of Science in Mathematics' },
          { value: 'bachelorScienceMechanicalEngineering', label: 'Bachelor of Science in Mechanical Engineering' },
          { value: 'bachelorScienceMedicalTechnology', label: 'Bachelor of Science in Medical Technology' },
          { value: 'bachelorScienceMeteorology', label: 'Bachelor of Science in Meteorology' },
          { value: 'bachelorScienceMicrobiology', label: 'Bachelor of Science in Microbiology' },
          { value: 'bachelorScienceMiningEngineering', label: 'Bachelor of Science in Mining Engineering' },
          { value: 'bachelorScienceMolecularBiology', label: 'Bachelor of Science in Molecular Biology' },
          { value: 'bachelorScienceNeuroscience', label: 'Bachelor of Science in Neuroscience' },
          { value: 'bachelorScienceNursing', label: 'Bachelor of Science in Nursing' },
          { value: 'bachelorScienceNutritionScience', label: 'Bachelor of Science in Nutrition science' },
          { value: 'bachelorScienceSoftwareEngineering', label: 'Bachelor of Science in Software Engineering' },
          { value: 'bachelorSciencePetroleumEngineering', label: 'Bachelor of Science in Petroleum Engineering' },
          { value: 'bachelorSciencePodiatry', label: 'Bachelor of Science in Podiatry' },
          { value: 'bachelorSciencePharmacology', label: 'Bachelor of Science in Pharmacology' },
          { value: 'bachelorSciencePharmacy', label: 'Bachelor of Science in Pharmacy' },
          { value: 'bachelorSciencePhysicalTherapy', label: 'Bachelor of Science in Physical Therapy' },
          { value: 'bachelorSciencePhysics', label: 'Bachelor of Science in Physics' },
          { value: 'bachelorSciencePlantScience', label: 'Bachelor of Science in Plant Science' },
          { value: 'bachelorSciencePolitics', label: 'Bachelor of Science in Politics' },
          { value: 'bachelorSciencePsychology', label: 'Bachelor of Science in Psychology' },
          { value: 'bachelorSciencePublicSafety', label: 'Bachelor of Science in Public Safety' },
          { value: 'bachelorScienceQuantitySurveyingEngineering', label: 'Bachelor of Science in Quantity Surveying Engineering' },
          { value: 'bachelorScienceRadiologicTechnology', label: 'Bachelor of Science in Radiologic Technology' },
          { value: 'bachelorScienceRealTimeInteractiveSimulation', label: 'Bachelor of Science in Real-Time Interactive Simulation' },
          { value: 'bachelorScienceReligion', label: 'Bachelor of Science in Religion' },
          { value: 'bachelorScienceRespiratoryTherapy', label: 'Bachelor of Science in Respiratory Therapy' },
          { value: 'bachelorScienceRiskManagementInsurance', label: 'Bachelor of Science in Risk Management and Insurance' },
          { value: 'bachelorScienceScienceEducation', label: 'Bachelor of Science in Science Education' },
          { value: 'bachelorScienceSportsManagement', label: 'Bachelor of Science in Sports Management' },
          { value: 'bachelorScienceSystemsEngineering', label: 'Bachelor of Science in Systems Engineering' },
          { value: 'bachelorMusicJazzStudies', label: 'Bachelor of Music in Jazz Studies' },
          { value: 'bachelorMusicComposition', label: 'Bachelor of Music in Composition' },
          { value: 'bachelorMusicPerformance', label: 'Bachelor of Music in Performance' },
          { value: 'bachelorMusicTheory', label: 'Bachelor of Music in Theory' },
          { value: 'bachelorMusicMusicEducation', label: 'Bachelor of Music in Music Education' },
          { value: 'bachelorScienceVeterinaryTechnology', label: 'Bachelor of Science in Veterinary Technology' },
          { value: 'other', label: 'Other' },
          { value: 'baSimple', label: 'BA Simple' },
          { value: 'daeAfterIntermediate', label: 'DAE after Intermediate' },
          { value: 'bbaHons', label: 'BBA Hons' },
          { value: 'bsHons', label: 'BS Hons' },
          { value: 'bTech', label: 'B.Tech' },
          { value: 'bTechIT', label: 'B.Tech IT' },
          { value: 'baBed', label: 'BA. BEd.' },
          { value: 'biotechnology', label: 'Biotechnology' },
          { value: 'bfdBachelorFashionDesigning', label: 'BFD Bachelor of Fashion Designing' },
          { value: 'bfdHons', label: 'BFD Hons' },
          { value: 'bsIslamiyat', label: 'BS Islamiyat' }
        ]
     case 'masters':
        return [
            { value: 'accountancy', label: 'Accountancy' },
            { value: 'advancedStudy', label: 'Advanced Study' },
            { value: 'appliedFinance', label: 'Applied Finance' },
            { value: 'appliedMathematicalSciences', label: 'Applied Mathematical Sciences' },
            { value: 'appliedScience', label: 'Applied Science.' },
            { value: 'architecture', label: 'Architecture.' },
            { value: 'arts', label: 'Arts.' },
            { value: 'artsLiberalStudies', label: 'Arts in Liberal Studies' },
            { value: 'artsStrategicCommunicationManagement', label: 'Arts in Strategic Communication Management' },
            { value: 'artsTeaching', label: 'Arts in Teaching' },
            { value: 'bioinformatics', label: 'Bioinformatics' },
            { value: 'mba', label: 'MBA.' },
            { value: 'mbaFinance', label: 'MBA Finance.' },
            { value: 'mbe', label: 'MBE.' },
            { value: 'businessEngineering', label: 'Business Engineering' },
            { value: 'businessInformatics', label: 'Business Informatics' },
            { value: 'chemistry', label: 'Chemistry.' },
            { value: 'cityPlanning', label: 'City Planning' },
            { value: 'mcom', label: 'M.Com.' },
            { value: 'computationalFinance', label: 'Computational Finance' },
            { value: 'computerScience', label: 'Computer Science.' },
            { value: 'counseling', label: 'Counseling' },
            { value: 'criminalJustice', label: 'Criminal Justice.' },
            { value: 'creativeTechnologies', label: 'Creative Technologies' },
            { value: 'design', label: 'Design.' },
            { value: 'economics', label: 'Economics.' },
            { value: 'education', label: 'Education.' },
            { value: 'educationalTechnology', label: 'Educational Technology' },
            { value: 'engineeringManagement', label: 'Engineering Management' },
            { value: 'english', label: 'English.' },
            { value: 'enterprise', label: 'Enterprise' },
            { value: 'europeanLaw', label: 'European Law' },
            { value: 'finance', label: 'Finance.' },
            { value: 'financialEconomics', label: 'Financial Economics' },
            { value: 'financialEngineering', label: 'Financial Engineering' },
            { value: 'financialMathematics', label: 'Financial Mathematics' },
            { value: 'fineArts', label: 'Fine Arts.' },
            { value: 'healthAdministration', label: 'Health Administration.' },
            { value: 'healthScience', label: 'Health Science.' },
            { value: 'humanities', label: 'Humanities' },
            { value: 'industrialLaborRelations', label: 'Industrial and Labor Relations' },
            { value: 'internationalAffairs', label: 'International Affairs' },
            { value: 'internationalBusiness', label: 'International Business' },
            { value: 'internationalEconomics', label: 'International Economics' },
            { value: 'internationalPublicPolicy', label: 'International Public Policy' },
            { value: 'internationalStudies', label: 'International Studies' },
            { value: 'informationManagement', label: 'Information Management.' },
            { value: 'islamicStudies', label: 'Islamic Studies.' },
            { value: 'masterIT', label: 'Master of IT' },
            { value: 'jurisprudence', label: 'Jurisprudence' },
            { value: 'llb', label: 'LLB.' },
            { value: 'llm', label: 'L.L.M.' },
            { value: 'landscapeArchitecture', label: 'Landscape Architecture.' },
            { value: 'liberalArts', label: 'Liberal Arts' },
            { value: 'libraryInformationScience', label: 'Library and Information Science' },
            { value: 'management', label: 'Management.' },
            { value: 'massCommunicationJournalism', label: 'Mass Communication and Journalism' },
            { value: 'mathematicalFinance', label: 'Mathematical Finance' },
            { value: 'mathematics', label: 'Mathematics.' },
            { value: 'mathematicsComputerScience', label: 'Mathematics and Computer Science' },
            { value: 'mathematicsPhilosophy', label: 'Mathematics and Philosophy' },
            { value: 'militaryArtScience', label: 'Military Art and Science' },
            { value: 'music', label: 'Music.' },
            { value: 'networkCommunicationsManagement', label: 'Network and Communications Management' },
            { value: 'occupationalTherapy', label: 'Occupational Therapy' },
            { value: 'pharmacy', label: 'Pharmacy.' },
            { value: 'philosophy', label: 'Philosophy.' },
            { value: 'physicianAssistantStudies', label: 'Physician Assistant Studies' },
            { value: 'physics', label: 'Physics.' },
            { value: 'politicalScience', label: 'Political Science.' },
            { value: 'professionalStudies', label: 'Professional Studies' },
            { value: 'psychology', label: 'Psychology.' },
            { value: 'publicAdministration', label: 'Public Administration.' },
            { value: 'publicAffairs', label: 'Public Affairs' },
            { value: 'publicDiplomacy', label: 'Public Diplomacy' },
            { value: 'publicHealth', label: 'Public Health.' },
            { value: 'publicManagement', label: 'Public Management' },
            { value: 'publicPolicy', label: 'Public Policy.' },
            { value: 'publicRelations', label: 'Public Relations' },
            { value: 'publicService', label: 'Public Service' },
            { value: 'quantitativeFinance', label: 'Quantitative Finance' },
            { value: 'rabbinicStudies', label: 'Rabbinic Studies' },
            { value: 'realEstateDevelopment', label: 'Real Estate Development' },
            { value: 'religiousEducation', label: 'Religious Education' },
            { value: 'research', label: 'Research.' },
            { value: 'sacredMusic', label: 'Sacred Music' },
            { value: 'sacredTheology', label: 'Sacred Theology' },
            { value: 'msc', label: 'MSc.' },
            { value: 'appliedCognitionNeuroscience', label: 'Applied Cognition and Neuroscience' },
            { value: 'clinicalEpidemiology', label: 'Clinical Epidemiology' },
            { value: 'computingResearch', label: 'Computing Research' },
            { value: 'cyberSecurity', label: 'Cyber Security' },
            { value: 'developmentAdministration', label: 'Development Administration' },
            { value: 'governanceOrganizationalSciences', label: 'Governance & Organizational Sciences' },
            { value: 'governmentContracts', label: 'Government Contracts' },
            { value: 'healthInformatics', label: 'Health Informatics' },
            { value: 'humanResourceDevelopment', label: 'Human Resource Development' },
            { value: 'informationAssurance', label: 'Information Assurance' },
            { value: 'informationSystems', label: 'Information Systems.' },
            { value: 'leadership', label: 'Leadership' },
            { value: 'nursing', label: 'Nursing.' },
            { value: 'projectManagement', label: 'Project Management' },
            { value: 'qualityAssurance', label: 'Quality Assurance' },
            { value: 'riskManagement', label: 'Risk Management.' },
            { value: 'supplyChainManagement', label: 'Supply Chain Management' },
            { value: 'taxation', label: 'Taxation' },
            { value: 'socialScience', label: 'Social Science' },
            { value: 'socialWork', label: 'Social Work.' },
            { value: 'statistics', label: 'Statistics.' },
            { value: 'strategicStudies', label: 'Strategic Studies' },
            { value: 'surgery', label: 'Surgery.' },
            { value: 'theologicalStudies', label: 'Theological Studies' },
            { value: 'sociology', label: 'Sociology' },
            { value: 'theology', label: 'Theology.' },
            { value: 'urbanPlanning', label: 'Urban Planning' },
            { value: 'urdu', label: 'Urdu.' },
            { value: 'veterinaryScience', label: 'Veterinary Science' },
            { value: 'other', label: 'Other' },
            { value: 'acca', label: 'ACCA' },
            { value: 'ca', label: 'C.A.' },
            { value: 'maLlb', label: 'MA, LLB' },
            { value: 'baLlb', label: 'BA, LLB' },
            { value: 'bcomLlb', label: 'B.Com, LLB' },
            { value: 'mcomLlb', label: 'M.Com, LLB' },
            { value: 'mscPhysics', label: 'MSc Physics' },
            { value: 'maMed', label: 'MA. MEd.' },
            { value: 'mbaFinanceMasters', label: 'MBA Finance' },
            { value: 'mastersHRM', label: 'Masters in Human Resource Management HRM' },
            { value: 'clinicalPsychology', label: 'Clinical Psychology' },
            { value: 'geology', label: 'Geology' },
            { value: 'biotechnology', label: 'Biotechnology' },
            { value: 'caAcca', label: 'CA, ACCA' },
            { value: 'caAccaCfa', label: 'CA, ACCA, CFA' },
            { value: 'llbHons', label: 'LLB Hons' },
            { value: 'artificialIntelligence', label: 'Artificial Intelligence' }
        ]
      case 'mphil':
        return [
            { value: 'microBiology', label: 'Micro-Biology' },
            { value: 'bioTechnology', label: 'Bio-Technology' },
            { value: 'islamicStudies', label: 'Islamic Studies' },
            { value: 'researchMethodology', label: 'Research Methodology' },
            { value: 'philosophicalPoliticalThoughts', label: 'Philosophical & Political thoughts of Quaid-i-Azam & Allama Iqbal.' },
            { value: 'geographyOfPakistan', label: 'Geography of Pakistan' },
            { value: 'politicalSystemOfPakistan', label: 'Political System of Pakistan' },
            { value: 'criminology', label: 'Criminology' },
            { value: 'other', label: 'Other' },
            { value: 'physics', label: 'Physics' },
            { value: 'pharmaceutics', label: 'Pharmaceutics' },
            { value: 'pharmaceuticalChemistry', label: 'Pharmaceutical Chemistry' },
            { value: 'pharmacology', label: 'Pharmacology' },
            { value: 'pharmacognosy', label: 'Pharmacognosy' },
            { value: 'clinicalPsycology', label: 'Clinical Psycology' },
            { value: 'chemistry', label: 'Chemistry' },
            { value: 'massCommunication', label: 'Mass Communication' },
            { value: 'optometry', label: 'Optometry' },
            { value: 'dermatology', label: 'Dermatology' },
            { value: 'morbidAnatomyHistopathology', label: 'Morbid Anatomy and Histopathology' },
            { value: 'dieteticsNutritionalSciences', label: 'Dietetics and Nutritional Sciences' },
            { value: 'education', label: 'Education' },
            { value: 'neuromuscularPhysicalTherapy', label: 'Neuromuscular Physical Therapy NMPT' },
            { value: 'sportsPhysicalTherapy', label: 'Sports Physical Therapy (SPT)' },
            { value: 'anatomy', label: 'Anatomy' },
            { value: 'physiology', label: 'Physiology' },
            { value: 'chemicalPathology', label: 'Chemical Pathology' },
            { value: 'histopathology', label: 'Histopathology' },
            { value: 'hematology', label: 'Hematology' },
            { value: 'mathematics', label: 'Mathematics' },
            { value: 'archaeology', label: 'Archaeology' },
            { value: 'sociology', label: 'Sociology' },
            { value: 'educationPolicyDevelopment', label: 'Education Policy & Development' },
            { value: 'genderStudies', label: 'Gender Studies' },
            { value: 'computerScience', label: 'Computer Science' },
            { value: 'remoteSensingGIS', label: 'Remote Sensing & Geographical Information System (RSGIS)' },
            { value: 'economics', label: 'Economics' },
            { value: 'polymerTechnology', label: 'Polymer Technology' },
            { value: 'molecularBiologyForensicSciences', label: 'Molecular Biology & Forensic Sciences' },
            { value: 'arabic', label: 'Arabic' },
            { value: 'iqbalStudies', label: 'Iqbal Studies' },
            { value: 'urdu', label: 'Urdu' },
            { value: 'educationalPlanningManagement', label: 'Educational Planning & Management EPM' },
            { value: 'statistics', label: 'Statistics' },
            { value: 'english', label: 'English' },
            { value: 'history', label: 'History' },
            { value: 'internationalRelation', label: 'International Relation' },
            { value: 'politicalScience', label: 'Political Science' },
            { value: 'libraryInformationSciences', label: 'Library & Information Sciences' },
            { value: 'zoology', label: 'Zoology' },
            { value: 'botany', label: 'Botany' },
            { value: 'englishLiterature', label: 'English Literature' },
            { value: 'environmentalSciences', label: 'Environmental Sciences' },
            { value: 'earstenMedicine', label: 'Earsten Medicine' },
            { value: 'geography', label: 'Geography' },
            { value: 'publicAdministration', label: 'Public Administration' },
            { value: 'commerce', label: 'Commerce' },
            { value: 'pharmacyPractice', label: 'Pharmacy Practice' },
            { value: 'ruralSociology', label: 'Rural Sociology' },
            { value: 'epidemiologyPublicHealth', label: 'Epidemiology & Public Health' },
            { value: 'forestryRangeManagement', label: 'Forestry & Range Management' },
            { value: 'wildlifeManagement', label: 'Wildlife & Management' },
            { value: 'anthropology', label: 'Anthropology' },
            { value: 'marketing', label: 'Marketing' },
            { value: 'finance', label: 'Finance' },
            { value: 'llm', label: 'LLM.' },
            { value: 'mediaCommunication', label: 'Media & Communication' },
            { value: 'computerTechnology', label: 'Computer Technology' },
            { value: 'islamicBankingFinance', label: 'Islamic Banking & Finance' },
            { value: 'organicChemistry', label: 'Organic Chemistry' },
            { value: 'analyticalPhysicalInorganicChemistry', label: 'Analytical/Physical/Inorganic Chemistry' },
            { value: 'bioOrganicChemistry', label: 'Bio Organic Chemistry' },
            { value: 'textileChemistry', label: 'Textile Chemistry' },
            { value: 'plantBiotechnology', label: 'Plant Biotechnology' },
            { value: 'molecularMedicine', label: 'Molecular Medicine' },
            { value: 'foodSafetyQualityManagement', label: 'Food Safety & Quality Management' },
            { value: 'molecularPathologyGenomics', label: 'Molecular Pathology & Genomics' },
            { value: 'genetics', label: 'Genetics' },
            { value: 'psychology', label: 'Psychology.' }
        ]
      case 'doctorate':
        return [
            { value: 'doctorBusinessAdministration', label: 'Doctor of Business Administration' },
            { value: 'doctorCanonLaw', label: 'Doctor of Canon Law' },
            { value: 'doctorChiropractic', label: 'Doctor of Chiropractic' },
            { value: 'doctorCommerce', label: 'Doctor of Commerce' },
            { value: 'doctorDentalSurgery', label: 'Doctor of Dental Surgery B.D.S.' },
            { value: 'doctorDivinity', label: 'Doctor of Divinity' },
            { value: 'doctorEducation', label: 'Doctor of Education' },
            { value: 'doctorEngineering', label: 'Doctor of Engineering' },
            { value: 'doctorHealthAdministration', label: 'Doctor of Health Administration' },
            { value: 'doctorHealthScience', label: 'Doctor of Health Science' },
            { value: 'doctorJuridicalScience', label: 'Doctor of Juridical Science; Juris Doctor' },
            { value: 'doctorLaw', label: 'Doctor of Law; Legum Doctor' },
            { value: 'doctorLiberalStudies', label: 'Doctor of Liberal Studies' },
            { value: 'doctorManagement', label: 'Doctor of Management' },
            { value: 'doctorMedicine', label: 'Doctor of Medicine M.B.B.S.' },
            { value: 'doctorMinistry', label: 'Doctor of Ministry' },
            { value: 'doctorMusicalArts', label: 'Doctor of Musical Arts' },
            { value: 'doctorNaturopathicMedicine', label: 'Doctor of Naturopathic Medicine' },
            { value: 'doctorOptometry', label: 'Doctor of Optometry' },
            { value: 'doctorOsteopathicMedicine', label: 'Doctor of Osteopathic Medicine' },
            { value: 'doctorPharmacy', label: 'Doctor of Pharmacy' },
            { value: 'doctorPhilosophy', label: 'Doctor of Philosophy' },
            { value: 'doctorPublicAdministration', label: 'Doctor of Public Administration' },
            { value: 'doctorScience', label: 'Doctor of Science' },
            { value: 'doctorTheology', label: 'Doctor of Theology' },
            { value: 'doctorVeterinaryMedicine', label: 'Doctor of Veterinary Medicine' },
            { value: 'other', label: 'Other' },
            { value: 'doctorHomeopathic', label: 'Doctor of Homeopathic' },
            { value: 'doctorPhysiotherapist', label: 'Doctor of Physiotherapist' },
            { value: 'doctorNutrition', label: 'Doctor of Nutrition' },
            { value: 'doctorMedicalImaging', label: 'Doctor of Medical Imaging' },
            { value: 'phdDoctor', label: 'PhD Doctor' }
        ]
      case 'engineer':
        return [
            { value: 'aerospaceEngineer', label: 'Aerospace Engineer' },
            { value: 'chemicalEngineer', label: 'Chemical Engineer' },
            { value: 'civilEngineer', label: 'Civil Engineer' },
            { value: 'computerEngineer', label: 'Computer Engineer' },
            { value: 'softwareEngineer', label: 'Software Engineer' },
            { value: 'electricalEngineer', label: 'Electrical Engineer' },
            { value: 'mechanicalEngineer', label: 'Mechanical Engineer' },
            { value: 'industrialEngineer', label: 'Industrial Engineer' },
            { value: 'biomedicalEngineer', label: 'Biomedical Engineer' },
            { value: 'biomechanicalEngineer', label: 'Biomechanical Engineer' },
            { value: 'automotiveEngineer', label: 'Automotive Engineer' },
            { value: 'structuralEngineer', label: 'Structural Engineer' },
            { value: 'architecturalEngineer', label: 'Architectural Engineer' },
            { value: 'mechatronicsEngineer', label: 'Mechatronics Engineer' },
            { value: 'roboticsEngineer', label: 'Robotics Engineer' },
            { value: 'microelectronicEngineer', label: 'Microelectronic Engineer' },
            { value: 'environmentalEngineer', label: 'Environmental Engineer' },
            { value: 'materialsScienceEngineer', label: 'Materials Science Engineer' },
            { value: 'agriculturalEngineer', label: 'Agricultural Engineer' },
            { value: 'paperEngineer', label: 'Paper Engineer' },
            { value: 'sustainabilityDesignEngineer', label: 'Sustainability Design Engineer' },
            { value: 'systemsEngineer', label: 'Systems Engineer' },
            { value: 'manufacturingEngineer', label: 'Manufacturing Engineer' },
            { value: 'petroleumEngineer', label: 'Petroleum Engineer' },
            { value: 'geologicalEngineer', label: 'Geological Engineer' },
            { value: 'nuclearEngineer', label: 'Nuclear Engineer' },
            { value: 'marineEngineer', label: 'Marine Engineer' },
            { value: 'photonicsEngineer', label: 'Photonics Engineer' },
            { value: 'nanotechnologyEngineer', label: 'Nanotechnology Engineer' },
            { value: 'miningEngineer', label: 'Mining Engineer' },
            { value: 'ceramicsEngineer', label: 'Ceramics Engineer' },
            { value: 'metallurgicalEngineer', label: 'Metallurgical Engineer' },
            { value: 'geomaticsEngineer', label: 'Geomatics Engineer' },
            { value: 'gamingEngineer', label: 'Gaming Engineer' },
            { value: 'textileEngineer', label: 'Textile Engineer' },
            { value: 'mbaChemicalEngineer', label: 'MBA, Chemical Engineer' },
            { value: 'artificialIntelligenceAi', label: 'Artificial Intelligence Ai' }
        ]
      default:
        return []
    }
  }